### ISSUE TITLE
Decoder fails when feature lacks tags

### ISSUE THREAD

**Issue by springmeyer** [ElectronicChartCentre/java-vector-tile#53]
Features in the MVT spec may lack tags (if no properties need to be encoded): https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features. This is uncommon, but possible. In this case java-vector-tile fails like:

```
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at no.ecc.vectortile.VectorTileDecoder$FeatureIterator.parseFeature(VectorTileDecoder.java:233)
	at no.ecc.vectortile.VectorTileDecoder$FeatureIterator.findNext(VectorTileDecoder.java:186)
	at no.ecc.vectortile.VectorTileDecoder$FeatureIterator.hasNext(VectorTileDecoder.java:149)
	at no.ecc.vectortile.VectorTileDecoder$FeatureIterable.asList(VectorTileDecoder.java:106)
```

Here is a testcase:

```
layers {
  name: "layer"
  features {
    id: 1
    tags: 0
    tags: 0
    type: POINT
    geometry: 9
    geometry: 50
    geometry: 34
  }
  version: 2
}
```

Convert that text into a protobuf encoded vector tile by saving the above text as a file called `point.txt` and then doing:

```
git clone https://github.com/mapbox/vector-tile-spec
protoc vector-tile-spec/2.1/vector_tile.proto --encode vector_tile.Tile < point.txt > point.mvt
```

**Comment by halset** [comment]
In this case there are two `tags: 0`, but no `keys` or `values`. The code tries to find the first `keys` for the first `tags: 0` and the first `values` from the second `tags: 0`. This is what is leading to index out of bounds exception.

Why is this case not encoded without the `tags: 0`?

How should this case be understood and handled? Is two `tags: 0` and no `keys` or `values` a special case meaning no feature attributes? 

I tried the decoder now without the two `tags: 0` and that worked fine.
```
layers {
  name: "layer"
  features {
    id: 1
    type: POINT
    geometry: 9
    geometry: 50
    geometry: 34
  }
  version: 2
}
```

**Comment by springmeyer** [comment]
Ah, thanks for your insight. Indeed the tags at the feature level were a typo. Thanks. The fixed example is what I intended to work. Sorry for the noise here!

**Comment by halset** [comment]
No problem. Thank you for the link to https://github.com/maplibre/maplibre-tile-spec and all the good work!
